Repository supernova-9th/yamyam-navi, pull requests merged in 2024-08, with the labels that each got.

#8 refactor: GlobalExceptionHandler 반환타입 변경
  src/main/java/com/yamyamnavi/api/GlobalExceptionHandler.java
Labels: 최하록, 🌈 REFACTOR

#11 feat: 도시 목록 조회 기능 구현
  src/main/java/com/yamyamnavi/api/CityController.java
  src/main/java/com/yamyamnavi/api/converter/CityConverter.java
  src/main/java/com/yamyamnavi/api/response/CityResponse.java
  src/main/java/com/yamyamnavi/api/response/SggResponse.java
  src/main/java/com/yamyamnavi/domain/city/CityFinder.java
  src/main/java/com/yamyamnavi/domain/city/CityRepository.java
  src/main/java/com/yamyamnavi/domain/city/CityService.java
  src/main/java/com/yamyamnavi/domain/city/CitySgg.java
  src/main/java/com/yamyamnavi/storage/city/CityCoreRepository.java
  src/test/java/com/yamyamnavi/api/CityResponseControllerTest.java
  src/test/java/com/yamyamnavi/api/converter/CityResponseConverterTest.java
  src/test/java/com/yamyamnavi/domain/city/CityResponseMockFinderTest.java
  src/test/java/com/yamyamnavi/domain/city/CityResponseMockServiceTest.java
Labels: 박소미, ✨ FEAT

#13 refactor: 패키지 구조 변경 (#5)
  src/main/java/com/yamyamnavi/api/v1/controller/CityController.java
  src/main/java/com/yamyamnavi/api/v1/converter/CityConverter.java
  src/main/java/com/yamyamnavi/api/v1/response/CityResponse.java
  src/main/java/com/yamyamnavi/api/v1/response/SggResponse.java
  src/main/java/com/yamyamnavi/domain/city/CityFinder.java
  src/main/java/com/yamyamnavi/domain/city/CityService.java
  src/main/java/com/yamyamnavi/storage/city/CityCoreRepository.java
  src/test/java/com/yamyamnavi/api/CityResponseControllerTest.java
  src/test/java/com/yamyamnavi/api/converter/CityResponseConverterTest.java
  src/test/java/com/yamyamnavi/domain/city/CityResponseMockFinderTest.java
  src/test/java/com/yamyamnavi/domain/city/CityResponseMockServiceTest.java
Labels: 박소미, 🌈 REFACTOR

#20 feat: 음식점 데이터 업로드 배치 구현
  build.gradle
  src/main/java/com/yamyamnavi/batch/CoordinateConverter.java
  src/main/java/com/yamyamnavi/batch/CustomRestaurantItemWriter.java
  src/main/java/com/yamyamnavi/batch/ScheduledBatchConfig.java
  src/main/java/com/yamyamnavi/batch/SeoulFacilityBatchConfig.java
  src/main/java/com/yamyamnavi/client/SeoulOpenApiClient.java
  src/main/java/com/yamyamnavi/client/SeoulOpenApiConfig.java
  src/main/java/com/yamyamnavi/client/response/SeoulApiResponse.java
  src/main/java/com/yamyamnavi/client/response/SeoulFacility.java
  src/main/java/com/yamyamnavi/config/JpaConfig.java
  src/main/java/com/yamyamnavi/storage/restaurant/RestaurantEntity.java
Labels: 최하록, ✨ FEAT

#15 feat: 맛집 상세 정보 조회 기능 구현
  src/main/java/com/yamyamnavi/api/v1/controller/CityController.java
  src/main/java/com/yamyamnavi/api/v1/controller/RestaurantController.java
  src/main/java/com/yamyamnavi/api/v1/converter/RestaurantConverter.java
  src/main/java/com/yamyamnavi/api/v1/response/CityResponse.java
  src/main/java/com/yamyamnavi/api/v1/response/RestaurantResponse.java
  src/main/java/com/yamyamnavi/api/v1/response/ReviewResponse.java
  src/main/java/com/yamyamnavi/api/v1/response/SggResponse.java
  src/main/java/com/yamyamnavi/config/QueryDslConfig.java
  src/main/java/com/yamyamnavi/domain/restaurant/Location.java
  src/main/java/com/yamyamnavi/domain/restaurant/RestaurantDetail.java
  src/main/java/com/yamyamnavi/domain/restaurant/RestaurantFinder.java
  src/main/java/com/yamyamnavi/domain/restaurant/RestaurantRepository.java
  src/main/java/com/yamyamnavi/domain/restaurant/RestaurantService.java
  src/main/java/com/yamyamnavi/domain/review/Review.java
  src/main/java/com/yamyamnavi/domain/review/ReviewFinder.java
  src/main/java/com/yamyamnavi/domain/review/ReviewRepository.java
  src/main/java/com/yamyamnavi/storage/restaurant/RestaurantCoreRepository.java
  src/main/java/com/yamyamnavi/storage/restaurant/RestaurantRepositoryImpl.java
  src/main/java/com/yamyamnavi/storage/review/ReviewCoreRepository.java
  src/main/java/com/yamyamnavi/storage/review/ReviewRepositoryImpl.java
  src/main/java/com/yamyamnavi/support/error/ErrorCode.java
  src/main/java/com/yamyamnavi/support/error/RestaurantNotFoundException.java
  src/test/java/com/yamyamnavi/api/converter/CityResponseConverterTest.java
Labels: 박소미, ✨ FEAT

#18 feat: 리뷰 생성 기능 구현
  src/main/java/com/yamyamnavi/api/v1/controller/ReviewController.java
  src/main/java/com/yamyamnavi/api/v1/converter/ReviewConverter.java
  src/main/java/com/yamyamnavi/api/v1/request/ReviewCreateRequest.java
  src/main/java/com/yamyamnavi/api/v1/response/ReviewResponse.java
  src/main/java/com/yamyamnavi/domain/review/Review.java
  src/main/java/com/yamyamnavi/domain/review/ReviewAppender.java
  src/main/java/com/yamyamnavi/domain/review/ReviewRepository.java
  src/main/java/com/yamyamnavi/domain/review/ReviewService.java
  src/main/java/com/yamyamnavi/storage/review/ReviewCoreRepository.java
  src/main/java/com/yamyamnavi/storage/review/ReviewEntity.java
  src/main/java/com/yamyamnavi/storage/review/converter/ReviewConverter.java
Labels: 이혜지, ✨ FEAT
