Repository supernova-9th/yamyam-navi, pull requests merged in 2024-09, with the labels that each got.

#23 feat: 리뷰 생성 및 가게 리뷰 업데이트 구현
  src/main/java/com/yamyamnavi/domain/restaurant/RestaurantDetail.java
  src/main/java/com/yamyamnavi/domain/restaurant/RestaurantRepository.java
  src/main/java/com/yamyamnavi/domain/restaurant/RestaurantReviewUpdater.java
  src/main/java/com/yamyamnavi/domain/review/Review.java
  src/main/java/com/yamyamnavi/domain/review/ReviewAppender.java
  src/main/java/com/yamyamnavi/domain/review/ReviewRepository.java
  src/main/java/com/yamyamnavi/domain/review/ReviewService.java
  src/main/java/com/yamyamnavi/storage/restaurant/RestaurantCoreRepository.java
  src/main/java/com/yamyamnavi/storage/restaurant/RestaurantRepositoryImpl.java
  src/main/java/com/yamyamnavi/storage/review/ReviewCoreRepository.java
  src/main/java/com/yamyamnavi/storage/review/ReviewEntity.java
  src/test/java/com/yamyamnavi/api/v1/controller/ReviewControllerTest.java
  src/test/java/com/yamyamnavi/api/v1/converter/ReviewConverterTest.java
  src/test/java/com/yamyamnavi/storage/review/converter/ReviewConverterTest.java
Labels: 이혜지, ✨ FEAT

#17 feat: 로그인 회원가입 기능 구현
  build.gradle
  src/main/java/com/yamyamnavi/api/v1/controller/TokenController.java
  src/main/java/com/yamyamnavi/api/v1/controller/UserController.java
  src/main/java/com/yamyamnavi/api/v1/converter/ReviewConverter.java
  src/main/java/com/yamyamnavi/api/v1/converter/UserConverter.java
  src/main/java/com/yamyamnavi/api/v1/request/SignInRequest.java
  src/main/java/com/yamyamnavi/api/v1/request/UserChangePasswordRequest.java
  src/main/java/com/yamyamnavi/api/v1/request/UserCreateRequest.java
  src/main/java/com/yamyamnavi/api/v1/request/UserUpdateLocationRequest.java
  src/main/java/com/yamyamnavi/api/v1/request/UserUpdateRequest.java
  src/main/java/com/yamyamnavi/api/v1/response/ReviewDetailResponse.java
  src/main/java/com/yamyamnavi/api/v1/response/TokenResponse.java
  src/main/java/com/yamyamnavi/api/v1/response/UserResponse.java
  src/main/java/com/yamyamnavi/config/JpaConfig.java
  src/main/java/com/yamyamnavi/config/RedisConfig.java
  src/main/java/com/yamyamnavi/config/SecurityConfig.java
  src/main/java/com/yamyamnavi/domain/location/GeoPoint.java
  src/main/java/com/yamyamnavi/domain/location/GeocodeService.java
  src/main/java/com/yamyamnavi/domain/token/TokenIssuer.java
  src/main/java/com/yamyamnavi/domain/user/User.java
  src/main/java/com/yamyamnavi/domain/user/UserAppender.java
  src/main/java/com/yamyamnavi/domain/user/UserFinder.java
  src/main/java/com/yamyamnavi/domain/user/UserLoginProcessor.java
  src/main/java/com/yamyamnavi/domain/user/UserRedisRepository.java
  src/main/java/com/yamyamnavi/domain/user/UserRepository.java
  src/main/java/com/yamyamnavi/domain/user/UserService.java
  src/main/java/com/yamyamnavi/domain/user/UserUpdater.java
  src/main/java/com/yamyamnavi/domain/user/UserValidator.java
  src/main/java/com/yamyamnavi/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/yamyamnavi/security/CustomUserDetailsService.java
  src/main/java/com/yamyamnavi/security/JwtProvider.java
  src/main/java/com/yamyamnavi/security/JwtTokenFilter.java
  src/main/java/com/yamyamnavi/security/LoginUser.java
  src/main/java/com/yamyamnavi/storage/user/UserCoreRepository.java
  src/main/java/com/yamyamnavi/storage/user/UserEntity.java
  src/main/java/com/yamyamnavi/storage/user/UserJpaRepository.java
  src/main/java/com/yamyamnavi/support/error/ErrorCode.java
  src/main/java/com/yamyamnavi/support/error/InvalidPasswordException.java
  src/main/java/com/yamyamnavi/support/error/InvalidPeriodException.java
  src/main/java/com/yamyamnavi/support/error/JwtValidateException.java
  src/main/java/com/yamyamnavi/support/error/UserNotFoundException.java
  src/main/java/com/yamyamnavi/support/error/UserRegistrationException.java
  src/test/java/com/yamyamnavi/api/v1/controller/ReviewControllerTest.java
  src/test/java/com/yamyamnavi/api/v1/controller/UserControllerTest.java
  src/test/java/com/yamyamnavi/api/v1/converter/ReviewConverterTest.java
  src/test/java/com/yamyamnavi/config/TestSecurityConfig.java
  src/test/java/com/yamyamnavi/security/JwtProviderTest.java
Labels: ✨ FEAT, 이소영

#26 refactor: 데이터 추가 배치 수정
  src/main/java/com/yamyamnavi/batch/CustomRestaurantItemWriter.java
  src/test/java/com/yamyamnavi/api/v1/controller/UserControllerTest.java
  src/test/java/com/yamyamnavi/config/TestSecurityConfig.java
  src/test/java/com/yamyamnavi/storage/review/converter/ReviewConverterTest.java
Labels: 최하록, 🌈 REFACTOR

#30 feat: 맛집 목록 조회 구현
  build.gradle
  src/main/java/com/yamyamnavi/api/v1/controller/RestaurantController.java
  src/main/java/com/yamyamnavi/api/v1/converter/RestaurantConverter.java
  src/main/java/com/yamyamnavi/api/v1/request/RestaurantSearchRequest.java
  src/main/java/com/yamyamnavi/api/v1/response/RestaurantDetailResponse.java
  src/main/java/com/yamyamnavi/domain/restaurant/Restaurant.java
  src/main/java/com/yamyamnavi/domain/restaurant/RestaurantFinder.java
  src/main/java/com/yamyamnavi/domain/restaurant/RestaurantRepository.java
  src/main/java/com/yamyamnavi/domain/restaurant/RestaurantService.java
  src/main/java/com/yamyamnavi/storage/restaurant/RestaurantCoreRepository.java
  src/main/java/com/yamyamnavi/storage/restaurant/RestaurantRepositoryImpl.java
  src/main/java/com/yamyamnavi/support/enums/RestaurantSort.java
  src/main/java/com/yamyamnavi/support/response/PageResponse.java
Labels: 박소미, ✨ FEAT

#31 refactor: 영업상태 조건 추가 (#16)
  src/main/java/com/yamyamnavi/storage/restaurant/RestaurantRepositoryImpl.java
Labels: 박소미, 🔨FIX

#29 fix: 첫 리뷰 작성 시 맛집 평점 평균 계산 버그 수정
  src/main/java/com/yamyamnavi/domain/restaurant/RestaurantDetail.java
  src/main/java/com/yamyamnavi/domain/review/ReviewService.java
  src/main/java/com/yamyamnavi/storage/restaurant/RestaurantCoreRepository.java
  src/main/java/com/yamyamnavi/storage/restaurant/RestaurantRepositoryImpl.java
Labels: 이혜지, 🔨FIX

#33 refactor: UserEntity 수정, 새비밀번호 암호화 (#3)
  src/main/java/com/yamyamnavi/api/v1/converter/UserConverter.java
  src/main/java/com/yamyamnavi/api/v1/response/UserResponse.java
  src/main/java/com/yamyamnavi/domain/user/User.java
  src/main/java/com/yamyamnavi/domain/user/UserFinder.java
  src/main/java/com/yamyamnavi/domain/user/UserRepository.java
  src/main/java/com/yamyamnavi/domain/user/UserService.java
  src/main/java/com/yamyamnavi/domain/user/UserUpdater.java
  src/main/java/com/yamyamnavi/security/LoginUser.java
  src/main/java/com/yamyamnavi/storage/user/UserCoreRepository.java
  src/main/java/com/yamyamnavi/storage/user/UserEntity.java
  src/main/java/com/yamyamnavi/storage/user/UserJpaRepository.java
Labels: ✨ FEAT, 이소영

#37 feat: csv 업로드 기능 구현
  build.gradle
  src/main/java/com/yamyamnavi/api/v1/controller/CityController.java
  src/main/java/com/yamyamnavi/api/v1/converter/CityConverter.java
  src/main/java/com/yamyamnavi/domain/city/CityAppender.java
  src/main/java/com/yamyamnavi/domain/city/CityConverter.java
  src/main/java/com/yamyamnavi/domain/city/CityFinder.java
  src/main/java/com/yamyamnavi/domain/city/CityRemover.java
  src/main/java/com/yamyamnavi/domain/city/CityRepository.java
  src/main/java/com/yamyamnavi/domain/city/CityService.java
  src/main/java/com/yamyamnavi/domain/restaurant/Restaurant.java
  src/main/java/com/yamyamnavi/storage/city/CityCoreRepository.java
  src/main/java/com/yamyamnavi/storage/restaurant/RestaurantRepositoryImpl.java
  src/main/java/com/yamyamnavi/support/error/ErrorCode.java
  src/main/java/com/yamyamnavi/support/error/FileUploadException.java
Labels: 박소미, ✨ FEAT

#36 feat: 사용자 위도, 경도 업데이트
  build.gradle
  src/main/java/com/yamyamnavi/api/v1/controller/UserController.java
  src/main/java/com/yamyamnavi/api/v1/converter/UserConverter.java
  src/main/java/com/yamyamnavi/api/v1/request/SignInRequest.java
  src/main/java/com/yamyamnavi/api/v1/request/UserChangePasswordRequest.java
  src/main/java/com/yamyamnavi/api/v1/request/UserCreateRequest.java
  src/main/java/com/yamyamnavi/api/v1/request/UserUpdateLocationRequest.java
  src/main/java/com/yamyamnavi/api/v1/request/UserUpdateRequest.java
  src/main/java/com/yamyamnavi/api/v1/response/UserResponse.java
  src/main/java/com/yamyamnavi/config/SecurityConfig.java
  src/main/java/com/yamyamnavi/domain/location/GeoPoint.java
  src/main/java/com/yamyamnavi/domain/location/GeocodeService.java
  src/main/java/com/yamyamnavi/domain/token/TokenIssuer.java
  src/main/java/com/yamyamnavi/domain/user/User.java
  src/main/java/com/yamyamnavi/domain/user/UserLoginProcessor.java
  src/main/java/com/yamyamnavi/domain/user/UserService.java
  src/main/java/com/yamyamnavi/security/JwtTokenFilter.java
  src/main/java/com/yamyamnavi/security/LoginUser.java
  src/main/java/com/yamyamnavi/storage/user/UserEntity.java
  src/main/java/com/yamyamnavi/support/error/InvalidPeriodException.java
Labels: ✨ FEAT, 이소영

#40 refactor: 맛집 상세 정보 조회시 리뷰 페이징 추가
  src/main/java/com/yamyamnavi/api/v1/controller/RestaurantController.java
  src/main/java/com/yamyamnavi/api/v1/controller/TokenController.java
  src/main/java/com/yamyamnavi/api/v1/converter/RestaurantConverter.java
  src/main/java/com/yamyamnavi/api/v1/converter/ReviewConverter.java
  src/main/java/com/yamyamnavi/api/v1/request/RestaurantDetailSearchRequest.java
  src/main/java/com/yamyamnavi/api/v1/response/RestaurantDetailPageResponse.java
  src/main/java/com/yamyamnavi/domain/restaurant/RestaurantDetail.java
  src/main/java/com/yamyamnavi/domain/restaurant/RestaurantService.java
  src/main/java/com/yamyamnavi/domain/review/ReviewFinder.java
  src/main/java/com/yamyamnavi/domain/review/ReviewRepository.java
  src/main/java/com/yamyamnavi/storage/restaurant/RestaurantEntity.java
  src/main/java/com/yamyamnavi/storage/review/ReviewCoreRepository.java
  src/main/java/com/yamyamnavi/storage/review/ReviewRepositoryImpl.java
  src/main/java/com/yamyamnavi/support/enums/ReviewSort.java
Labels: 박소미, 🌈 REFACTOR
